config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin  # noqa
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # path(
    #     "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    # ),
    # Django Admin, use {% url 'admin:index' %}
    # path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("read_comics.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

read_comics/users/urls.py
from django.urls import path

from read_comics.users.views import (
    user_redirect_view,
    user_edit_view,
    user_detail_view,
    user_change_photo_view,
    user_delete_photo_view,
    user_send_email_confirmation_view
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("edit/", view=user_edit_view, name="edit"),
    path("change_photo/", view=user_change_photo_view, name="change_photo"),
    path("delete_photo/", view=user_delete_photo_view, name="delete_photo"),
    path("send_email_confirmation", view=user_send_email_confirmation_view, name="send_email_confirmation"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

read_comics/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from utils import logging
from utils.fields import ThumbnailImageField


logger = logging.getLogger(__name__)


def get_user_image_name(instance, filename):
    return "publisher_logo/{0}_logo.{1}".format(instance.name, filename.split('.')[-1])


class User(AbstractUser):
    class Gender(models.TextChoices):
        MALE = 'M', _('Male')
        FEMALE = 'F', _('Female')
        UNICORN = 'U', _('Unicorn')
        OTHER = 'O', _('Other')

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Full name"), blank=True, max_length=255)
    gender = models.CharField(_("Gender"), max_length=1, choices=Gender.choices, default=Gender.UNICORN)
    _user_image = ThumbnailImageField(null=True, upload_to=get_user_image_name,
                                      thumb_width=40)
    bio = models.CharField(_("Bio"), blank=True, max_length=1000)
    birth_date = models.DateField(_("Birth date"), null=True, blank=True)
    show_email = models.BooleanField(_("Show email in profile"), default=False)
    last_active = models.DateTimeField(_("Last active"), null=True)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

    @property
    def image_url(self):
        if self._user_image:
            return self._user_image.url
        else:
            return "/static/images/avatars/{0}.png".format(self.gender)

    @property
    def image_thumb_url(self):
        if self._user_image:
            return self._user_image.thumb_url
        else:
            return "/static/images/avatars/{0}_thumb.png".format(self.gender)

    def __str__(self):
        return self.name or self.username.title()

    @logging.logged(logger)
    def save(self, *args, **kwargs):
        if not self.name:
            if self.first_name and self.last_name:
                self.name = "%s %s" % (self.first_name, self.last_name)
            elif self.first_name:
                self.name = self.first_name
            elif self.last_name:
                self.name = self.last_name
        super(User, self).save(*args, **kwargs)

read_comics/users/views.py
import allauth.account.signals
from allauth.account.adapter import get_adapter
from allauth.account.utils import logout_on_password_change
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import DetailView, RedirectView, UpdateView, ListView
import django_magnificent_messages as dmm

from users.forms import UserInfoForm, ChangePasswordForm
from utils import logging
from utils.view_mixins import BreadcrumbMixin

User = get_user_model()
logger = logging.getLogger(__name__)


class UserListView(BreadcrumbMixin, ListView):
    model = User


class UserDetailView(BreadcrumbMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    context_object_name = "user"
    template_name = "users/user_detail.html"

    def get_breadcrumb(self):
        user = self.get_object()
        return [
            {'url': "#", 'text': "Users"},
            {'url': reverse_lazy("users:detail", args=(user.username,)), 'text': str(user)}
        ]


user_detail_view = UserDetailView.as_view()


class UserSendEmailConfirmationView(LoginRequiredMixin, RedirectView):
    @logging.logged(logger)
    def get(self, request, *args, **kwargs):
        email = request.user.emailaddress_set.get(primary=True)
        if not email.verified:
            email.send_confirmation(request)
            get_adapter(self.request).add_message(
                self.request,
                messages.INFO,
                'account/messages/'
                'email_confirmation_sent.txt',
                {'email': email})
        return super(UserSendEmailConfirmationView, self).get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return self.request.GET.get("next", reverse_lazy("home"))


user_send_email_confirmation_view = UserSendEmailConfirmationView.as_view()


class UserEditView(BreadcrumbMixin, LoginRequiredMixin, UpdateView):
    model = User
    breadcrumb = [{'url': reverse_lazy("users:edit"), 'text': 'Edit profile'}]
    context_object_name = "user"
    info_form_class = UserInfoForm
    password_form_class = ChangePasswordForm

    @logging.logged(logger)
    def get_form(self, form_class=None):
        kwargs = self.get_form_kwargs()
        if 'info' in self.request.POST:
            logger.debug("form: info")
            return self.info_form_class(**kwargs)
        elif 'password' in self.request.POST:
            logger.debug("form: password")
            user = kwargs.pop('instance')
            kwargs['user'] = user
            return self.password_form_class(**kwargs)

    @logging.logged(logger)
    def get_context_data(self, **kwargs):
        context = super(UserEditView, self).get_context_data(**kwargs)
        if not context.get('info_form'):
            context['info_form'] = self.info_form_class(instance=self.get_object())
        if not context.get('password_form'):
            context['password_form'] = self.password_form_class()
        show_tab = self.request.GET.get("show_tab")
        if show_tab:
            context['show_tab'] = show_tab
        return context

    def get_success_url(self):
        return reverse_lazy("users:edit")

    def get_object(self, queryset=None):
        return User.objects.get(username=self.request.user.username)

    @logging.logged(logger)
    def form_valid(self, form):
        if 'info' in self.request.POST:
            logger.debug("form: info success")
            dmm.notifications.success(self.request, "Info successfully updated")
            email = self.request.user.emailaddress_set.get(primary=True)
            if form.cleaned_data["email"] != email.email:
                email.change(self.request, form.cleaned_data["email"])
                get_adapter(self.request).add_message(
                    self.request,
                    messages.INFO,
                    'account/messages/'
                    'email_confirmation_sent.txt',
                    {'email': email})
            return super().form_valid(form)
        elif 'password' in self.request.POST:
            logger.debug("form: password success")
            form.save()
            logout_on_password_change(self.request, form.user)
            get_adapter(self.request).add_message(
                self.request,
                messages.SUCCESS,
                'account/messages/password_set.txt')
            allauth.account.signals.password_set.send(sender=self.request.user.__class__,
                                                      request=self.request, user=self.request.user)
            return HttpResponseRedirect(self.get_success_url())

    @logging.logged(logger)
    def form_invalid(self, form):
        context = {}
        if 'info' in self.request.POST:
            logger.debug("form: info errors")
            dmm.notifications.error(self.request, "Please check entered data", "Can't save info")
            context = {'info_form': form, 'show_tab': 'info'}
        elif 'password' in self.request.POST:
            logger.debug("form: password errors")
            dmm.notifications.error(self.request, "Please check entered data", "Can't change password")
            context = {'password_form': form, 'show_tab': 'password'}
        return self.render_to_response(self.get_context_data(**context))


user_edit_view = UserEditView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class UserChangePhotoView(LoginRequiredMixin, View):
    @logging.logged(logger)
    def post(self, request):
        user = request.user
        user.user_image = request.FILES['file']
        user.save()
        return JsonResponse(data={"image_url": user.image_url})


user_change_photo_view = UserChangePhotoView.as_view()


class UserDeletePhotoView(LoginRequiredMixin, View):
    @logging.logged(logger)
    def post(self, request):
        user = request.user
        user.user_image = None
        user.save()
        return JsonResponse(data={"image_url": user.image_url})


user_delete_photo_view = UserDeletePhotoView.as_view()

read_comics/users/templates/users/user_detail.html
{% extends "base.html" %}
{% load static humanize %}

{% block title %}User: {{ user }}{% endblock %}

{% block page_vendor_css %}
  <link rel="stylesheet" type="text/css" href="{% static "users/css/profile.css" %}">
{% endblock %}

{% block page_header %}
  User detail
{% endblock %}

{% block page_css %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static "users/css/social.css" %}">
{% endblock %}

{% block page_content %}
  <!-- page user profile start -->
  <section class="page-user-profile">
    <div class="row">
      <div class="col-12">
        <!-- user profile heading section start -->
        <div class="card">
          <div class="card-content">
            <div class="user-profile-images">
              <!-- user timeline image -->
              <div class="img-fluid rounded-top user-timeline-image bg-success"></div>
              <!-- user profile image -->
              <img src="{{ user.image_url }}" class="user-profile-image rounded bg-white"
                   alt="user profile image" height="140" width="140">
            </div>
            <!-- user profile nav tabs start -->
            <div class="card-body px-0">

              <div class="user-profile-text">
                {% if user.name %}
                  <h4 class="mb-0 text-bold-500 profile-text-color">{{ user.name }}</h4>
                  <small>@{{ user.username }}</small>
                {% else %}
                {% endif %}
              </div>
              <ul
                  class="nav user-profile-nav justify-content-center justify-content-md-start nav-tabs border-bottom-0 mb-0"
                  role="tablist">
                <li class="nav-item pb-0">
                  <a class="nav-link d-flex px-1 active" id="profile-tab" data-toggle="tab"
                     href="#profile"
                     aria-controls="profile" role="tab" aria-selected="false">
                    <i class="fad fa-info mr-50"></i> <span class="d-none d-md-block pl-50"> Info</span></a>
                </li>
                <li class="nav-item pb-0">
                  <a class="nav-link d-flex px-1" id="social-tab" data-toggle="tab"
                     href="#social"
                     aria-controls="social" role="tab" aria-selected="false">
                    <i class="fad fa-share-alt mr-50"></i> <span class="d-none d-md-block pl-50"> Social accounts</span></a>
                </li>
              </ul>
            </div>
            <!-- user profile nav tabs ends -->
          </div>
        </div>
        <!-- user profile heading section ends -->

        <!-- user profile content section start -->
        <div class="row">
          <!-- user profile nav tabs content start -->
          <div class="col-12">
            <div class="tab-content">
              <div class="tab-pane active" id="profile" aria-labelledby="profile-tab" role="tabpanel">
                <div class="row">
                  <div class="col-12">
                    <div class="card">
                      <div class="card-content">
                        <div class="card-body">
                          <h5 class="card-title">Info</h5>
                          <ul class="list-unstyled">
                            <li><strong>Gender:</strong> {{ user.get_gender_display }}</li>
                            {% if user.show_email %}
                              <li><strong>Email:</strong> {{ user.email }}</li>
                            {% endif %}
                            <li><strong>Birth date:</strong> {{ user.birth_date }}</li>
                            <li><strong>Registered:</strong> {{ user.date_joined|date }}</li>
                            <li><strong>Last active:</strong> {{ user.last_active|naturaltime }}</li>
                          </ul>
                          <div class="row">
                            <div class="col-12">
                              <h6><strong>Bio</strong></h6>
                              <p>{{ user.bio|default_if_none:"" }}</p>
                            </div>
                          </div>
                          {% if user == request.user %}
                            <a class="btn btn-sm d-block float-right btn-light-success mb-2 cursor-pointer"
                               href="{% url "users:edit" %}">
                              <i class="fad fa-edit font-small-3 mr-50"></i><span>Edit</span>
                            </a>
                          {% endif %}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="tab-pane fade" id="social" aria-labelledby="social-tab" role="tabpanel">
                 <div class="row">
                  <div class="col-12">
                    <div class="card">
                      <div class="card-content">
                        <div class="card-body">
                          <h5 class="card-title">Social accounts</h5>
                          {% include "users/social/list.html" %}
                        </div>
                      </div>
                    </div>
                  </div>
                 </div>
              </div>
              </div>
            </div>
            <!-- user profile nav tabs content ends -->

          </div>
          <!-- user profile content section start -->
        </div>
      </div>
  </section>
  <!-- page user profile ends -->

{% endblock page_content %}

read_comics/users/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags static socialaccount %}

{% block title %}Edit profile{% endblock %}

{% block page_header %}
  Edit profile
{% endblock %}

{% block page_vendor_css %}
  <link rel="stylesheet" type="text/css" href="{% static "_frest/vendors/css/pickers/pickadate/pickadate.css" %}">
{% endblock %}

{% block page_css %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static "users/css/social.css" %}">
{% endblock %}

{% block page_content %}
  <section id="page-account-settings">
    <div class="row">
      <div class="col-12">
        <div class="row">
          <!-- left menu section -->
          <div class="col-md-3 mb-2 mb-md-0 pills-stacked">
            <ul class="nav nav-pills flex-column">
              <li class="nav-item">
                <a class="nav-link d-flex align-items-center {% if not show_tab or show_tab == 'info' %}active{% endif %}"
                   id="account-pill-info" data-toggle="pill"
                   href="#account-vertical-info" aria-expanded="false">
                  <i class="fad fa-info-circle"></i>
                  <span>Info</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link d-flex align-items-center {% if show_tab == 'password' %}active{% endif %}"
                   id="account-pill-password" data-toggle="pill"
                   href="#account-vertical-password" aria-expanded="false">
                  <i class="fad fa-lock-alt"></i>
                  <span>Change Password</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link d-flex align-items-center {% if show_tab == 'social' %}active{% endif %}"
                   id="account-pill-social" data-toggle="pill"
                   href="#account-vertical-connections" aria-expanded="false">
                  <i class="fad fa-share-alt"></i>
                  <span>Social accounts</span>
                </a>
              </li>
            </ul>
          </div>
          <!-- right content section -->
          <div class="col-md-9">
            <div class="card">
              <div class="card-content">
                <div class="card-body">
                  <h3>@{{ user.username }}</h3>
                <hr>
                  <div class="tab-content">
                    <div class="tab-pane {% if not show_tab or show_tab == 'info' %}active{% else %}fade{% endif %}"
                         id="account-vertical-info" role="tabpanel"
                         aria-labelledby="account-pill-info" aria-expanded="true">
                      <div class="media">
                        <a href="javascript: void(0);">
                          <img src="{{ user.image_url }}"
                               class="rounded mr-75" alt="profile image" height="64" width="64" id="user_photo">
                        </a>
                        <div class="media-body mt-25">
                          <div
                              class="col-12 px-0 d-flex flex-sm-row flex-column justify-content-start">
                            <button id="select-photo"
                                    class="btn btn-sm btn-light-success ml-50 mb-50 mb-sm-0">Upload new photo
                            </button>
                            <button id="delete-photo" class="btn btn-sm btn-light-danger ml-50">Delete photo</button>
                          </div>
                          <p class="text-muted ml-1 mt-50"><small>Allowed JPG, GIF or PNG. Please select square image or
                            it may display very strange</small></p>
                        </div>
                      </div>
                                            <hr>
                      {% crispy info_form %}
                    </div>
                    <div class="tab-pane {% if show_tab == 'password' %}active{% else %}fade{% endif %}"
                         id="account-vertical-password" role="tabpanel"
                         aria-labelledby="account-pill-password" aria-expanded="false">
                      {% crispy password_form %}
                    </div>

                    <div class="tab-pane {% if show_tab == 'social' %}active{% else %}fade{% endif %}"
                         id="account-vertical-connections" role="tabpanel"
                         aria-labelledby="account-pill-connections" aria-expanded="false">
                      <p class="text-muted my-50"><small>You can use this social accounts to login instead of your
                        username/password</small></p>
                      {% include "users/social/list.html" %}
                      <hr>
                      {% include "account/social_buttons.html" with soc_process="connect" %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- account setting page ends -->
{% endblock %}

{% block vendor_js %}
  <script src="{% static "_frest/vendors/js/extensions/dropzone.min.js" %}"></script>
  <script src="{% static "_frest/vendors/js/pickers/pickadate/picker.js" %}"></script>
  <script src="{% static "_frest/vendors/js/pickers/pickadate/picker.date.js" %}"></script>
{% endblock %}

{% block page_js %}
  <script>
    let change_photo_url = "{% url "users:change_photo" %}";
    let delete_photo_url = "{% url "users:delete_photo" %}";
    let activeTab = "{{ show_tab }}"
  </script>
  <script src="{% static "users/js/edit_user.js" %}"></script>
{% endblock %}