config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin  # noqa
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # path(
    #     "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    # ),
    # Django Admin, use {% url 'admin:index' %}
    # path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("read_comics.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

read_comics/users/urls.py
from django.urls import path

from read_comics.users.views import (
    user_redirect_view,
    user_edit_view,
    user_detail_view,
    user_change_photo_view,
    user_delete_photo_view,
    user_send_email_confirmation_view
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("edit/", view=user_edit_view, name="edit"),
    path("change_photo/", view=user_change_photo_view, name="change_photo"),
    path("delete_photo/", view=user_delete_photo_view, name="delete_photo"),
    path("send_email_confirmation", view=user_send_email_confirmation_view, name="send_email_confirmation"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

read_comics/characters/models.py
from django.db import models
from utils.models import ComicvineSyncModel


class Character(ComicvineSyncModel):
    name = models.TextField()
    aliases = models.TextField()
    short_description = models.TextField()
    html_description = models.TextField()

    thumb_url = models.URLField(max_length=1000)
    image_url = models.URLField(max_length=1000)

read_comics/people/models.py
from django.db import models
from django_extensions.db.fields import AutoSlugField

from utils.models import ComicvineSyncModel, slugify_function


class Person(ComicvineSyncModel):
    name = models.TextField(null=True)
    aliases = models.TextField(null=True)
    short_description = models.TextField(null=True)
    html_description = models.TextField(null=True)

    birth_date = models.DateField(null=True)
    death_date = models.DateField(null=True)

    hometown = models.TextField(null=True)
    country = models.TextField(null=True)

    thumb_url = models.URLField(max_length=1000, null=True)
    image_url = models.URLField(max_length=1000, null=True)

    slug = AutoSlugField(populate_from=["name"], slugify_function=slugify_function)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return "[Person] %s (%d)" % (self.name, self.pk)

read_comics/users/forms.py
import allauth.account.forms
import allauth.socialaccount.forms
from crispy_forms.layout import Field, Layout, Div, HTML, Row, Column, Submit
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm, Textarea
from django.utils.translation import ugettext_lazy as _

from utils.form_helpers import DefaultFormHelper

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):
    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])


class ModelFormRequiredMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True


class UserInfoForm(ModelFormRequiredMixin, ModelForm):

    class Meta:
        model = User
        fields = ['name', 'gender', 'birth_date', 'show_email', 'bio', 'email']
        widgets = {
            'bio': Textarea(),
        }
        required = ['email']

    helper = DefaultFormHelper()
    helper.attrs = {"novalidate": "novalidate"}

    helper.layout = Layout(
        Row(
            Column(Field('name')),
            Column(Field('email')),
        ),
        Row(
            Column(Field('gender')),
            Column(Field('birth_date')),
        ),
        Field('show_email'),
        Field('bio'),
        HTML("<hr>"),
        Div(
            Submit(name="info", value="Save", css_class="btn btn-success"),
            css_class="d-flex flex-sm-row flex-column justify-content-end"
        )
    )


class LoginForm(allauth.account.forms.LoginForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        self.fields["login"].widget.attrs.pop("autofocus")
        self.fields["password"].widget.attrs.update({
            "autocomplete": "current-password"
        })
        self.fields["remember"].label = _("<small>Remember Me</small>")

        self.helper = DefaultFormHelper()
        self.helper.attrs = {"novalidate": "novalidate"}

        self.helper.layout = Layout(
            Field("login", wrapper_class="mb-50"),
            Field("password"),
            Div(
                Div(
                    Field("remember", wrapper_class="checkbox-sm"),
                    css_class="text-left"
                ),
                HTML(
                    """<div class="text-right">
                        <a href="{% url "account_reset_password" %}" class="card-link">
                            <small>Forgot Password?</small>
                        </a>
                    </div>"""),
                css_class="form-group d-flex flex-md-row flex-column justify-content-between align-items-center"
            ),
            HTML("""<button type="submit" class="btn btn-success glow w-100 position-relative">
                    Login<i id="icon-arrow" class="bx bx-right-arrow-alt"></i>
                    </button>""")
        )


class ResetPasswordForm(allauth.account.forms.ResetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(ResetPasswordForm, self).__init__(*args, **kwargs)

        self.helper = DefaultFormHelper()
        self.helper.attrs = {"novalidate": "novalidate"}
        self.helper.form_class = "mb-2"

        self.helper.layout = Layout(
            Field("email", wrapper_class="mb-2"),
            HTML("""
            <button type="submit" class="btn btn-success glow position-relative w-100">
            RESET PASSWORD<i id="icon-arrow" class="bx bx-right-arrow-alt"></i>
            </button>
            """)
        )


class ChangePasswordForm(allauth.account.forms.ChangePasswordForm):
    def __init__(self, *args, **kwargs):
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

        self.helper = DefaultFormHelper()
        self.helper.attrs = {"novalidate": "novalidate"}

        self.helper.layout = Layout(
            Field('oldpassword'),
            Field('password1'),
            Field('password2'),
            HTML("<hr>"),
            Div(
                Submit(name="password", value="Save", css_class="btn btn-success"),
                css_class="d-flex flex-sm-row flex-column justify-content-end"
            )
        )


class ResetPasswordKeyForm(allauth.account.forms.ResetPasswordKeyForm):
    def __init__(self, *args, **kwargs):
        super(ResetPasswordKeyForm, self).__init__(*args, **kwargs)

        self.helper = DefaultFormHelper()
        self.helper.attrs = {"novalidate": "novalidate"}
        self.helper.form_class = "mb-2"

        self.fields["password1"].widget.attrs.update({
            "autocomplete": "new-password"
        })
        self.fields["password2"].widget.attrs.update({
            "autocomplete": "new-password"
        })

        self.helper.layout = Layout(
            Field("password1"),
            Field("password2", wrapper_class="mb-2"),
            HTML("""
            <button type="submit" class="btn btn-success glow position-relative w-100">
            Reset my password<i id="icon-arrow" class="bx bx-right-arrow-alt"></i>
            </button>
            """)
        )


class SignupForm(allauth.account.forms.SignupForm):
    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)

        self.helper = DefaultFormHelper()
        self.helper.attrs = {"novalidate": "novalidate"}

        self.fields["username"].widget.attrs.pop("autofocus")
        self.fields["username"].widget.attrs.update({
            "autocomplete": "username"
        })
        self.fields["password1"].widget.attrs.update({
            "autocomplete": "new-password"
        })
        self.fields["password2"].widget.attrs.update({
            "autocomplete": "new-password"
        })

        self.helper.layout = Layout(
            Field("username", wrapper_class="mb-50"),
            Field("email", wrapper_class="mb-50"),
            Field("password1", wrapper_class="mb-50"),
            Field("password2", wrapper_class="mb-2"),
            HTML("""
            <button type="submit" class="btn btn-success glow position-relative w-100">
            SIGN UP<i id="icon-arrow" class="bx bx-right-arrow-alt"></i>
            </button>
            """)
        )


class SocialSignupForm(allauth.socialaccount.forms.SignupForm):
    def __init__(self, *args, **kwargs):
        super(SocialSignupForm, self).__init__(*args, **kwargs)

        self.helper = DefaultFormHelper()
        self.helper.attrs = {"novalidate": "novalidate"}

        self.fields["username"].widget.attrs.pop("autofocus")

        self.helper.layout = Layout(
            Field("username", wrapper_class="mb-50"),
            Field("email", wrapper_class="mb-50"),
            HTML("""
                    <button type="submit" class="btn btn-success glow position-relative w-100">
                    SIGN UP<i id="icon-arrow" class="bx bx-right-arrow-alt"></i>
                    </button>
                    """)
        )

read_comics/characters/views.py
from django.shortcuts import render  # noqa

# Create your views here.

read_comics/users/views.py
import allauth.account.signals
from allauth.account.adapter import get_adapter
from allauth.account.utils import logout_on_password_change
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import DetailView, RedirectView, UpdateView, ListView
import django_magnificent_messages as dmm

from users.forms import UserInfoForm, ChangePasswordForm
from utils import logging
from utils.view_mixins import BreadcrumbMixin

User = get_user_model()
logger = logging.getLogger(__name__)


class UserListView(BreadcrumbMixin, ListView):
    model = User


class UserDetailView(BreadcrumbMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    context_object_name = "user"
    template_name = "users/user_detail.html"

    def get_breadcrumb(self):
        user = self.get_object()
        return [
            {'url': "#", 'text': "Users"},
            {'url': reverse_lazy("users:detail", args=(user.username,)), 'text': str(user)}
        ]


user_detail_view = UserDetailView.as_view()


class UserSendEmailConfirmationView(LoginRequiredMixin, RedirectView):
    @logging.logged(logger)
    def get(self, request, *args, **kwargs):
        email = request.user.emailaddress_set.get(primary=True)
        if not email.verified:
            email.send_confirmation(request)
            get_adapter(self.request).add_message(
                self.request,
                messages.INFO,
                'account/messages/'
                'email_confirmation_sent.txt',
                {'email': email})
        return super(UserSendEmailConfirmationView, self).get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return self.request.GET.get("next", reverse_lazy("home"))


user_send_email_confirmation_view = UserSendEmailConfirmationView.as_view()


class UserEditView(BreadcrumbMixin, LoginRequiredMixin, UpdateView):
    model = User
    breadcrumb = [{'url': reverse_lazy("users:edit"), 'text': 'Edit profile'}]
    context_object_name = "user"
    info_form_class = UserInfoForm
    password_form_class = ChangePasswordForm

    @logging.logged(logger)
    def get_form(self, form_class=None):
        kwargs = self.get_form_kwargs()
        if 'info' in self.request.POST:
            logger.debug("form: info")
            return self.info_form_class(**kwargs)
        elif 'password' in self.request.POST:
            logger.debug("form: password")
            user = kwargs.pop('instance')
            kwargs['user'] = user
            return self.password_form_class(**kwargs)

    @logging.logged(logger)
    def get_context_data(self, **kwargs):
        context = super(UserEditView, self).get_context_data(**kwargs)
        if not context.get('info_form'):
            context['info_form'] = self.info_form_class(instance=self.get_object())
        if not context.get('password_form'):
            context['password_form'] = self.password_form_class()
        show_tab = self.request.GET.get("show_tab")
        if show_tab:
            context['show_tab'] = show_tab
        return context

    def get_success_url(self):
        return reverse_lazy("users:edit")

    def get_object(self, queryset=None):
        return User.objects.get(username=self.request.user.username)

    @logging.logged(logger)
    def form_valid(self, form):
        if 'info' in self.request.POST:
            logger.debug("form: info success")
            dmm.notifications.success(self.request, "Info successfully updated")
            email = self.request.user.emailaddress_set.get(primary=True)
            if form.cleaned_data["email"] != email.email:
                email.change(self.request, form.cleaned_data["email"])
                get_adapter(self.request).add_message(
                    self.request,
                    messages.INFO,
                    'account/messages/'
                    'email_confirmation_sent.txt',
                    {'email': email})
            return super().form_valid(form)
        elif 'password' in self.request.POST:
            logger.debug("form: password success")
            form.save()
            logout_on_password_change(self.request, form.user)
            get_adapter(self.request).add_message(
                self.request,
                messages.SUCCESS,
                'account/messages/password_set.txt')
            allauth.account.signals.password_set.send(sender=self.request.user.__class__,
                                                      request=self.request, user=self.request.user)
            return HttpResponseRedirect(self.get_success_url())

    @logging.logged(logger)
    def form_invalid(self, form):
        context = {}
        if 'info' in self.request.POST:
            logger.debug("form: info errors")
            dmm.notifications.error(self.request, "Please check entered data", "Can't save info")
            context = {'info_form': form, 'show_tab': 'info'}
        elif 'password' in self.request.POST:
            logger.debug("form: password errors")
            dmm.notifications.error(self.request, "Please check entered data", "Can't change password")
            context = {'password_form': form, 'show_tab': 'password'}
        return self.render_to_response(self.get_context_data(**context))


user_edit_view = UserEditView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class UserChangePhotoView(LoginRequiredMixin, View):
    @logging.logged(logger)
    def post(self, request):
        user = request.user
        user.user_image = request.FILES['file']
        user.save()
        return JsonResponse(data={"image_url": user.image_url})


user_change_photo_view = UserChangePhotoView.as_view()


class UserDeletePhotoView(LoginRequiredMixin, View):
    @logging.logged(logger)
    def post(self, request):
        user = request.user
        user.user_image = None
        user.save()
        return JsonResponse(data={"image_url": user.image_url})


user_delete_photo_view = UserDeletePhotoView.as_view()

read_comics/templates/blocks/layout/header/header.html
<!-- BEGIN: Header-->
<div class="header-navbar-shadow"></div>
<nav class="header-navbar main-header-navbar navbar-expand-lg navbar navbar-with-menu fixed-top ">
  <div class="navbar-wrapper">
    <div class="navbar-container content">
      <div class="navbar-collapse" id="navbar-mobile">
        <div class="mr-auto float-left bookmark-wrapper d-flex align-items-center">
          <ul class="nav navbar-nav">
            <li class="nav-item mobile-menu d-xl-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs"
                                                                  href="#"><i class="ficon bx bx-menu success"></i></a>
            </li>
          </ul>
          <ul class="nav navbar-nav bookmark-icons">
            <li class="nav-item d-none d-lg-block">
              <a class="nav-link" href="{% url "home" %}" data-toggle="tooltip" data-placement="top" title="Home">
                <i class="fad fa-home ficon success"></i>
              </a>
            </li>

          </ul>
        </div>
        <ul class="nav navbar-nav float-right">
          <li class="nav-item nav-search"><a class="nav-link nav-link-search"><i
              class="ficon fad fa-search success"></i></a>
            <div class="search-input">
              <div class="search-input-icon"><i class="fad fa-search success"></i></div>
              <input class="input" type="text" placeholder="Search..." tabindex="-1" data-search="starter-list">
              <div class="search-input-close"><i class="fas fa-times"></i></div>
              <ul class="search-list"></ul>
            </div>
          </li>
          {% if request.user.is_authenticated %}
            {% include "blocks/layout/header/messages.html" %}
            <li class="dropdown dropdown-user nav-item">
              <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
                <div class="user-nav d-sm-flex d-none">
                  <span class="user-name success">{{ request.user }}</span>
                </div>
                <span>
                <img class="round" src="{{ request.user.image_thumb_url }}" alt="avatar"
                     height="40" width="40">
              </span>
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="{% url "users:redirect" %}">
                  <i class="bx bx-user mr-50"></i> My Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="bx bx-envelope mr-50"></i> My Inbox
                </a>
                <a class="dropdown-item" href="#">
                  <i class="bx bx-check-square mr-50"></i> Task
                </a>
                <a class="dropdown-item" href="#">
                  <i class="bx bx-message mr-50"></i> Chats
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url "account_logout" %}">
                  <i class="bx bx-power-off mr-50"></i> Logout
                </a>
              </div>
            </li>
          {% else %}
            <li class="dropdown dropdown-language nav-item">
              <a class="nav-link" id="sign-in-link"
                 href="{% url 'account_login' %}?next={{ request.get_full_path }}">
                <span class="selected-language success font-medium-3">Sign in </span> <i
                  class="fad fa-sign-in success font-medium-5"></i>
              </a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
</nav>
<!-- END: Header-->

read_comics/templates/blocks/layout/header/messages.html
{% load static %}
<li class="dropdown dropdown-notification nav-item">
  <a class="nav-link nav-link-label" href="#" data-toggle="dropdown">
    <i class="ficon fad fa-bell success"></i>
    {% if dmm.messages.unread_count > 0 or not email_verified %}
      <span class="badge badge-pill badge-primary badge-up">
        {% include "blocks/layout/header/unread_count.html" %}
      </span>
    {% endif %}
  </a>
  <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
    <li class="dropdown-menu-header bg-success">
      <div class="dropdown-header px-1 py-75 d-flex justify-content-between">
        <span class="notification-title">{% include "blocks/layout/header/unread_count.html" %} unread message(s)</span>
        {% if dmm.messages.unread_count > 0 %}
          <span class="text-bold-400 cursor-pointer">Mark all as read</span>
        {% endif %}
      </div>
    </li>
    {% include "blocks/layout/header/verify_email_message.html" %}
    {% if dmm.messages.unread_count > 0 %}
      <li class="dropdown-menu-footer">
        <a class="dropdown-item p-50 text-primary justify-content-center" href="javascript:void(0)">
          Read all messages
        </a>
      </li>
    {% endif %}
  </ul>
</li>

read_comics/templates/blocks/layout/header/unread_count.html
{% if email_verified %}
  {{ dmm.messages.unread_count }}
{% else %}
  {{ dmm.messages.unread_count|add:1}}
{% endif %}

read_comics/templates/blocks/layout/header/verify_email_message.html
{% load static %}

{% if not email_verified %}
  <li class="scrollable-container media-list">
    <div class="d-flex justify-content-between">
      <div class="media d-flex align-items-center py-0">
        <div class="media-left pr-0">
          <img class="mr-1" src="{% static "images/logo.png" %}" alt="avatar" height="39"
               width="39">
        </div>
        <div class="media-body">
          <h6 class="media-heading">
            <span class="text-bold-500">Confirm your email</span>
          </h6>
          <small class="notification-text">Your email is not verified. Please confirm email</small>
        </div>
        <div class="media-right pl-0">
          <div class="row border-left text-center height-75">
            <div class="col-12 px-50 height-75 cursor-pointer div-link" style="padding-top: 30px;">
              <a href="{% url "users:send_email_confirmation" %}?next={{ request.get_full_path }}" class="div-default-link"></a>
              <h6 class="media-heading text-bold-500 mb-0">Confirm</h6>
            </div>

          </div>
        </div>
      </div>
    </div>
  </li>
{% endif %}